services:
  pensionados-apirest:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: back-pensionados:v0.1
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER_NAME: ${DB_USER_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - dokploy-network
    restart: always
    depends_on:
      db_pensionados:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pensionados.rule=Host(`181.32.123.173`)"
      - "traefik.http.routers.pensionados.entrypoints=web"
      - "traefik.http.services.pensionados.loadbalancer.server.port=8080"
 
  db_pensionados:
    image: mysql:8.0.40
    networks:
      - dokploy-network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

networks:
  dokploy-network:
    external: true