package com.unicauca.pensionados.back_pensionados.capaAccesoADatos.enums;


public enum TipoEvento {
    FALLECIMIENTO,
    SUSTITUCION,
    RELIQUIDACION,
    LIQUIDACION_INICIAL,
    REACTIVACION,
    SUSPENSION,
    REINTEGRO,
    AJUSTE_VALOR,
    CAMBIO_ESTADO,
    CAMBIO_BENEFICIARIO,
    ACTUALIZACION_DATOS,
    CREACION_PENSIONADO,
    CREACION_SUCESOR
}
